import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { Song } from '../utils/types'

const Home: NextPage = () => {
  const [songs, setSongs] = useState<Song[]>([])

  useEffect(() => {
    fetch('/api/getSongs')
      .then((response) => response.json())
      .then((data) => setSongs(data))
  }, [])

  console.log(songs)

  return (
    <div className='h-screen w-screen bg-slate-800'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='text-white'>Hello world</h1>
    </div>
  )
}

export default Home
